name: Lucas Rafaldini
markdown: kramdown
disqus:
    shortname: outras-ideias

# Social Media
social:
  github: lucasrafaldini
  linkedin: lucasrafaldini
  dev: lucasrafaldini

# Performance
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []



# SEO
seo:
  title: "Lucas Rafaldini - Engenheiro de Software"
  description: "Portfólio pessoal de Lucas Rafaldini - Engenheiro de Software especializado em Cibersegurança"
  keywords: "Lucas Rafaldini, Engenheiro de Software, Cibersegurança, Tecnologia, Desenvolvimento"
  author: "Lucas Rafaldini"
  image: "/assets/images/og-image.png"
  twitter:
    card: "summary_large_image"
    creator: "@lucasrafaldini"
  facebook:
    app_id: ""
